@startuml
start
->
:api/user/v1/role/addUserRole给用户分配角色(追加角色或减少角色);
->
:获取操作者信息;
->
:对请求参数中的userIds进行遍历;
->
:根据userId查找userVo;
->
if(userVo.isNotEmpty)then(y)
->
:addUserRole;
->
:根据customerId,userId查询出state不为9的qxUserCustomer对象;
->
:根据qxUserCustomer的id查出qxUserRole中没有的qxUserCustomer;
->
:保存qxUserRole;
endif
->
:返回true;
end
@enduml